# Generated by Django 5.0.6 on 2024-06-29 10:23

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('student_no', models.CharField(max_length=20, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True, validators=[registration.models.validate_email])),
                ('phone_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
