# Generated by Django 5.0.7 on 2024-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
