# Generated by Django 5.0.7 on 2024-09-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
